# Generated by Django 5.0.6 on 2024-06-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_total'),
        ('products', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 1)), name='order_amount_more_than_0'),
        ),
    ]
