# Generated by Django 5.0.6 on 2024-06-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NW', 'Новый'), ('IN', 'В обработке'), ('RD', 'Готов'), ('FN', 'Завершен')], default='NW', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
