# Generated by Django 5.0.6 on 2024-06-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filler',
            field=models.CharField(max_length=100, null=True, verbose_name='Наполнитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hard_materials',
            field=models.BooleanField(default=False, null=True, verbose_name='Элементы из жестких материалов'),
        ),
        migrations.AddField(
            model_name='product',
            name='knitting_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип вязки'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=100, null=True, verbose_name='Материал вязки'),
        ),
    ]
