# Generated by Django 5.0.6 on 2024-06-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_filler_product_is_hard_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filler',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наполнитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='knitting_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип вязки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал вязки'),
        ),
    ]
