# Generated by Django 5.0.6 on 2024-06-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_filler_alter_product_knitting_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(blank=True, help_text='В российских рублях', null=True, verbose_name='Старая цена'),
        ),
    ]
