# Generated by Django 5.0.6 on 2024-05-29 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_groups_alter_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteitem',
            options={'verbose_name': 'Товар в избранном пользователя', 'verbose_name_plural': 'Товары в избранном пользователя'},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteitem',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_favoritelist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='favoriteitem',
            name='user',
        ),
    ]
