# Generated by Django 5.0.6 on 2024-05-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_slug'),
        ('users', '0007_alter_favoritelist_options_favoriteitem_favoritelist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteitem',
            unique_together={('favoritelist', 'product')},
        ),
    ]
